name: 'Mayhem for API'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CONTAINER_NAME: 'mapi-action-examples'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.3.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: docker/mapi.dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    outputs:
      image: ${{ steps.meta.outputs.tags }}


  mapi:
    name: Run Mayhem for API to check for vulnerabilities
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Set up API
    - name: Run API container
      run: docker run --rm -d --network host --name ${{ env.CONTAINER_NAME }} ${{ needs.build.outputs.image }}

    # Run mAPI
    - uses: ForAllSecure/mapi-action@v1
      name: Run Mayhem for API
      continue-on-error: true
      with:
        mapi-token: ${{ secrets.MAPI_TOKEN }}
        api-url: http://localhost:8000
        api-spec: http://localhost:8000/openapi.json
        target: forallsecure/mapi-action-examples/fastapi
        sarif-report: mapi.sarif
        html-report: mapi.html

    # Kill python if it's still running, ignoring any errors
    - name: Shut down API
      run: docker exec ${{ env.CONTAINER_NAME }} bash -c 'pgrep coverage | xargs kill || true; sleep 5'

    # Run coverage
    - name: Generate coverage.xml
      run: docker exec ${{ env.CONTAINER_NAME }} bash -c 'coverage xml'

    # Copy coverage
    - name: Copy coverage
      run: docker cp ${{ env.CONTAINER_NAME }}:/api/coverage.xml .

    # Stop API
    - name: Stop API container
      run: docker kill ${{ env.CONTAINER_NAME }}

    # github codecov action
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        flags: vulnerability-tests
        name: mayhem
        fail_ci_if_error: true

    # Archive HTML report
    - name: Archive Mayhem for API report
      uses: actions/upload-artifact@v3
      with:
        name: mapi-report
        path: mapi.html

    # Upload SARIF file (only available on public repos or github enterprise)
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: mapi.sarif
